project:
  type: website

website:
  title: "ISSS624"
  navbar:
    left: 
      - text: Hands-on Exercises
        menu: 
          - text: "1A: Geospatial Data Wrangling with R"
            href: Hands-on_Ex1/Hands-on_Ex1.html
          - text: "1B: Choropleth Mapping with R"
            href: Hands-on_Ex1/Hands-on_Ex1_b.html
          - text: "2A: Spatial Weights and Application"
            href: Hands-on_Ex2/Hands-on_Ex2_a.html
          - text: "2B: Global Measures of Spatial Autocorrelation"
            href: Hands-on_Ex2/Hands-on_Ex2_b.html
          - text: "2C: Local Measures of Spatial Autocorrelation"
            href: Hands-on_Ex2/Hands-on_Ex2_c.html
          - text: "3: Processing and Visualising Flow Data"
            href: Hands-on_Ex3/Hands-on_Ex3.html
      - text: In-class Exercises
        menu: 
          - text: In-class Exercise 1
            href: In-class Ex/In-class_Ex1/In-class_Ex1.html
          - text: In-class Exercise 2A
            href: In-class Ex/In-class_Ex2/In-class_Ex2.html
          - text: In-class Exercise 2B
            href: In-class Ex/In-class_Ex2/In-class_Ex2_GSLA.html
          - text: In-class Exercise 2C
            href: In-class Ex/In-class_Ex2/In-class_Ex2_EHSA.html
      - text: Take-home Exercises
        menu: 
          - text: Take-Home Exercise 1
            #href: Take-Home_Ex/Take-Home_Ex1/Take-Home_Ex1.html
          - text: Take-home Exercise 2
            #href: 
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

