project:
  type: website

website:
  title: "ISSS624"
  navbar:
    left: 
      - text: Hands-on Exercises
        menu: 
          - text: Hands-on Exercise 1A
            href: Hands-on_Ex1/Hands-on_Ex1.html
          - text: Hands-on Exercise 1B
            href: Hands-on_Ex1/Hands-on_Ex1_b.html
          - text: Hands-on Exercise 2A
            href: Hands-on_Ex2/Hands-on_Ex2_a.html
          - text: Hands-on Exercise 2B
            href: Hands-on_Ex2/Hands-on_Ex2_b.html
          - text: Hands-on Exercise 2C
            href: Hands-on_Ex2/Hands-on_Ex2_c.html
          - text: Hands-on Exercise 3
            href: Hands-on_Ex3/Hands-on_Ex3.html
          - text: Hands-on Exercise 4
            href: Hands-on_Ex4/Hands-on_Ex4.html
      - text: In-class Exercises
        menu: 
          - text: In-class Exercise 1
            href: In-class Ex/In-class_Ex1/In-class_Ex1.html
          - text: In-class Exercise 2A
            href: In-class Ex/In-class_Ex2/In-class_Ex2.html
          - text: In-class Exercise 2B
            href: In-class Ex/In-class_Ex2/In-class_Ex2_GSLA.html
          - text: In-class Exercise 2C
            href: In-class Ex/In-class_Ex2/In-class_Ex2_EHSA.html
          - text: In-class Exercise 3
            href: In-class Ex/In-class_Ex3/In-class_Ex3.html
          - text: In-class Exercise 4
            href: In-class Ex/In-class_Ex4/In-class_Ex4.html
          - text: In-class Exercise 5
            href: In-class Ex/In-class_Ex5/In-class_Ex5.html
      - text: Take-home Exercises
        menu: 
          - text: Take-Home Exercise 1
            href: Take-Home_Ex/Take-Home_Ex1/Take-Home_Ex1.html
          - text: Take-home Exercise 2
            href: Take-Home_Ex/Take-Home_Ex2/Take-Home_Ex2.html
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

