project:
  type: website

website:
  title: "ISSS624"
  navbar:
    left: 
      - text: Hands-on Exercises
        menu: 
          - text: "1A: Geospatial Data Wrangling with R"
            href: Hands-on_Ex1/Hands-on_Ex1.html
          - text: "1B: Choropleth Mapping with R"
            href: Hands-on_Ex1/Hands-on_Ex1_b.html
      - text: In-class Exercises
        menu: 
          - text: In-class Exercise 1
            href: In-class Ex/In-class_Ex1/In-class_Ex1.html
          - text: In-class Exercise 2
            #href: In-class Ex/In-class_Ex2/In-class_Ex2.html
      - text: Take-home Exercises
        menu: 
          - text: Take-home Exercise 1
            #href:
          - text: Take-home Exercise 2
            #href: 
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

